name: Axentra
version: 1.0-SNAPSHOT
main: mc.ollie.App
api-version: 1.13
description: A custom server management plugin
author: OlliesWorld

commands:
  clear:
    description: Clears the player's inventory
    usage: /clear
    aliases: [c]
  repair:
    description: Repairs the item in your hand
    usage: /repair
    aliases: [r]
  axentra:
    description: Main Axentra command
    usage: /axentra <reload|upgrade|help|information>
    aliases: [ax]
  kick:
    description: Kicks a player from the server
    usage: /kick <player> [reason]
  ban:
    description: Bans a player from the server
    usage: /ban <player> [reason]
  unban:
    description: Unbans a player from the server
    usage: /unban <player>

permissions:
  Axentra.admin:
    description: Allows access to all /axentra subcommands
    default: op
  Axentra.clear:
    description: Allows the player to clear their inventory
    default: op
  Axentra.repair:
    description: Allows the player to repair their held item
    default: op
  Axentra.kick:
    description: Allows the player to kick others
    default: op
  Axentra.ban:
    description: Allows the player to ban others
    default: op
  Axentra.unban:
    description: Allows the player to unban others
    default: op