name: Axentra
version: 1.0.0-alpha
main: mc.ollie.App
api-version: 1.21
description: A custom server management plugin
author: OlliesWorld

commands:
  clear:
    description: Clears the player's inventory
    usage: /clear [player]
    aliases: [c]
  repair:
    description: Repairs the item in your hand
    usage: /repair
    aliases: [r]
  kick:
    description: Kicks a player from the server
    usage: /kick <player> [reason]
  ban:
    description: Bans a player from the server
    usage: /ban <player> [reason]
  unban:
    description: Unbans a player from the server
    usage: /unban <player>
  fly:
    description: Toggle flight mode for yourself or others
    usage: /fly [player]
  axentra:
    description: Main Axentra command
    usage: /axentra <reload | upgrade | help | information>
    aliases: [ax]

permissions:
  Axentra.admin:
    description: Allows access to all /axentra subcommands
    default: op
  Axentra.clear:
    description: Allows the player to clear their inventory
    default: op
  Axentra.clear.others:
    description: Allows the player to clear others' inventory
    default: op
  Axentra.repair:
    description: Allows the player to repair their held item
    default: op
  Axentra.kick:
    description: Allows the player to kick others
    default: op
  Axentra.ban:
    description: Allows the player to ban others
    default: op
  Axentra.unban:
    description: Allows the player to unban others
    default: op
  Axentra.fly:
    description: Allows the player to toggle flight
    default: op
  Axentra.fly.others:
    description: Allows the player to toggle flight for others
    default: op